server:
  port: 8080

spring:
  application:
    name: spring-boot-kafka-redis
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: "first-kafka-topic"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    hostname: localhost
    port: 6379

